services:
  web:
    image: tuanpham0012/new-admin-app:latest
    ports:
      - "8181:80"
    networks:
      - app-net
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "9000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"
networks:
  app-net:
    driver: overlay