# Tên của workflow, sẽ hiển thị trong tab "Actions" của GitHub
name: CI-CD Docker Push

# Cấu hình khi nào workflow sẽ được kích hoạt
on:
  push:
    branches: [ "main" ] # Chạy khi có push lên nhánh "main"
  pull_request:
    branches: [ "main" ] # Chạy khi có pull request vào nhánh "main"

# Định nghĩa các công việc (jobs) sẽ chạy
jobs:
  build-and-push:
    # Chạy trên một máy ảo Ubuntu phiên bản mới nhất
    runs-on: ubuntu-latest

    # Các bước thực hiện trong job này
    steps:
      # Bước 1: Checkout mã nguồn từ repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Đăng nhập vào Docker Hub
      # Sử dụng các secret đã tạo ở Bước 2
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Bước 3: Tự động tạo metadata (tên và tag) cho image
      # Ví dụ: yourdockerid/your-repo:latest, yourdockerid/your-repo:commit-sha
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

      # Bước 4: Build và push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}